### ISSUE TITLE
There are many problems with the installation though msys2

### ISSUE THREAD

**Issue by violetcodet** [TSchlosser13/Hexnet#2]
Probably caused by the version update
Can i have some version information about packages?

**Comment by TSchlosser13** [comment]
Hi, thank you for your feedback. I never had any problems with the MSYS2 installation. What error messages are you receiving? Can you try the following dependencies: [pacman_query.txt](https://github.com/TSchlosser13/Hexnet/files/8398644/pacman_query.txt)

**Comment by TSchlosser13** [comment]
Update: fixed as of 08/04/2022 via `./configure LDFLAGS="-lws2_32"` (ImageMagick installation)
